#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

// KORVO1 V5 音频I2S引脚配置 - ES7210 专用（根据原理图）
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_20
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_9
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_39

// KORVO1 V5 ES8311 专用 I2S 引脚配置（根据原理图）
#define AUDIO_ES8311_I2S_GPIO_MCLK GPIO_NUM_NC  // MCLK 未连接
#define AUDIO_ES8311_I2S_GPIO_WS   GPIO_NUM_41  // LRCK -> ESP_IO41
#define AUDIO_ES8311_I2S_GPIO_BCLK GPIO_NUM_40  // SCLK -> ESP_IO40
#define AUDIO_ES8311_I2S_GPIO_DOUT GPIO_NUM_39  // DSDIN -> ESP_IO39  

// KORVO1 V5 音频编解码器配置 - ES7210三阵列麦克风 + ES8311播放
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_38  // MUTE_BIN_OD_L - 功放使能引脚
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1   // KORVO1-V5官方文档
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2   // KORVO1-V5官方文档
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR  // 根据I2C扫描结果，ES8311实际地址为0x18
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR  // 根据I2C扫描结果，ES7210实际地址为0x40

// KORVO1 V5 三阵列麦克风配置
#define AUDIO_MIC_ARRAY_CHANNELS 3  // 三阵列麦克风
#define AUDIO_MIC_ARRAY_SPACING  65 // 麦克风间距(mm)

// 按钮配置
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_5
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// 多按键配置 - 6个按键连接到GPIO8
#define MULTI_BUTTON_GPIO       GPIO_NUM_8
#define MULTI_BUTTON_COUNT      6

// KORVO1 V5 WS2812 LED配置
#define WS2812_LED_GPIO         GPIO_NUM_19  // WS2812数据引脚
#define WS2812_LED_COUNT        12           // WS2812 LED数量

// KORVO1 V5 没有显示屏
#define DISPLAY_WIDTH   0
#define DISPLAY_HEIGHT  0
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// KORVO1 V5 没有摄像头
#define CAMERA_PIN_PWDN -1
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK -1
#define CAMERA_PIN_SIOD -1
#define CAMERA_PIN_SIOC -1
#define CAMERA_PIN_D7 -1
#define CAMERA_PIN_D6 -1
#define CAMERA_PIN_D5 -1
#define CAMERA_PIN_D4 -1
#define CAMERA_PIN_D3 -1
#define CAMERA_PIN_D2 -1
#define CAMERA_PIN_D1 -1
#define CAMERA_PIN_D0 -1
#define CAMERA_PIN_VSYNC -1
#define CAMERA_PIN_HREF -1
#define CAMERA_PIN_PCLK -1

#define XCLK_FREQ_HZ 20000000

#endif // _BOARD_CONFIG_H_ 